[package]
name = "rurl"
version = "0.1.0"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
openssl = "0.10"

[[bin]]
name = "rurl"
path = "src/main.rs"